### ISSUE TITLE
モバイル出し分け

### ISSUE THREAD

**Issue by ytkt** [ytkt/MyToDo#5]
PCとスマホでHTML出し分けします

**Comment by chashuumai** [comment]
マストヘッド
![20130920_02](https://f.cloud.github.com/assets/5194780/1681325/f5e88cda-5d90-11e3-9b93-4c8e84bf623a.jpg)

タスク
![d9fce01e233111e3822b22000a1f901c_7](https://f.cloud.github.com/assets/5194780/1681327/febfd232-5d90-11e3-9b2b-ab771363a57f.jpg)

終わった
![e72d9b5e230c11e3a3d522000a9f13e2_7](https://f.cloud.github.com/assets/5194780/1681328/0436d1b6-5d91-11e3-8eb3-bef97e731696.jpg)

**Comment by chashuumai** [comment]
PC

```
<div class="container">
    <%= yield %>
</div>
```

スマホ

```
<div class="mobile">
    <%= yield %>
</div>
```
